services:
  redis-gateway:
    image: redis:7.2-alpine
    container_name: gateway_rate_limiter
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local